# Generated by Django 4.2.5 on 2023-09-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_remove_postcategory_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
